### ISSUE TITLE
Build instructions ... 

### ISSUE THREAD

**Issue by maroparo** [dmarks2/liferay-plugin-intellij#2]
This is more a request than an issue. Can you provide a short documentation on how to build this ?

**Comment by maroparo** [comment]
`./gradlew clean build` did the trick.

**Comment by dmarks2** [comment]
Hey @maroparo, 
you are right, just run a gradle build. This is mentioned in the readme.md in the section "developers". 
If you have further questions or remarks about my plugin, just ask.
Regards,
 Dominik
