### ISSUE TITLE
Liferay server don't start with last version plugin

### ISSUE THREAD

**Issue by havana9** [dmarks2/liferay-plugin-intellij#5]
There is an error when starting the liferay server with the latest version of the plugin(2.0.0). The test has benn done with Liferay dxp 7.0.6 bundles and tomcat 8.0.32 and jdk 1.8.0B22. I test with 18.0.32 and jre 1.8 too. if i start the liferay server with 1.9.4 plugin version everything works correctly.

![liferay-intellij-plugin-error](https://user-images.githubusercontent.com/1156495/151412404-98940350-1640-408b-b206-e5a9b56d4b9f.PNG)

**Comment by dmarks2** [comment]
I think you are referring to the official plugin from Liferay at https://github.com/liferay/liferay-intellij-plugin. 

The problem you mention has already been fixed there, see https://github.com/liferay/liferay-intellij-plugin/issues/174.

I will close this issue as duplicate.
