### ISSUE TITLE
I have a question about LiferayJspDebuggerPositionManager class. 

### ISSUE THREAD

**Issue by simonjhy** [dmarks2/liferay-plugin-intellij#6]
@dmarks2 I have a question about LiferayJspDebuggerPositionManager line 56. Do we need to override the method locationsOfLine in LiferayJspDebuggerPositionManager class because we have a compatible issue wtih Intellij EAP versioni about the ReferenceType.  Can we discuss this when you have free time? We can discuss in liferay slack community.  

Package not found (1 problem)
Package 'com.sun.jdi' is not found (1 problem)
Package 'com.sun.jdi' is not found along with its 4 classes.
Probably the package 'com.sun.jdi' belongs to a library or dependency that is not resolved by the checker.
It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to NoSuchClassError.
The following classes of 'com.sun.jdi' are not resolved:
Class ReferenceType is referenced in
LiferayJspDebuggerPositionManager._locationsOfClassAt(...)
LiferayJspDebuggerPositionManager.access$000(...)
LiferayJspDebuggerPositionManager.access$400(...)
LiferayJspDebuggerPositionManager$1.<init>(...)
LiferayJspDebuggerPositionManager$1._getSourceName(...)
.

**Comment by dmarks2** [comment]
closing the issue as we already discussed about it
